
# Gem::Specification for Attr_splat-0
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: attr_splat
version: !ruby/object:Gem::Version 
  version: "0"
platform: ruby
authors: 
- elliottcable
autorequire: 
bindir: bin

date: 2008-10-09 00:00:00 -08:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: 3.0.1
    version: 
- !ruby/object:Gem::Dependency 
  name: rspec
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: rcov
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: yard
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: stringray
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: attr_* puts Ruby Core's attr_accessor, attr_reader, and attr_reader on steroids
email: 
- attr_splat@elliottcable.com
executables: []

extensions: []

extra_rdoc_files: 
- lib/attr_splat.rb
- README.markdown
files: 
- lib/attr_splat.rb
- Rakefile.rb
- README.markdown
- spec/attr_splat_spec.rb
- spec/spec_helper.rb
- .manifest
- attr_splat.gemspec
has_rdoc: true
homepage: http://by.elliottcable.name/attr_splat.xhtml
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Attr_splat
- --main
- README.markdown
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: attr_splat
rubygems_version: 1.3.0
specification_version: 2
summary: attr_* puts Ruby Core's attr_accessor, attr_reader, and attr_reader on steroids
test_files: []
